export const member = []

export const picture = [
  'https://www.techtalkthai.com/wp-content/uploads/2019/05/stack_overflow_banner_1.jpg',
  'https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded',
  'https://upload.wikimedia.org/wikipedia/commons/d/dd/Stack_Overflow_Home.png',
  'https://www.techtalkthai.com/wp-content/uploads/2019/05/stack_overflow_banner_1.jpg',
  'https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded',
  'https://upload.wikimedia.org/wikipedia/commons/d/dd/Stack_Overflow_Home.png',
  'https://www.techtalkthai.com/wp-content/uploads/2019/05/stack_overflow_banner_1.jpg',
  'https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded',
  'https://upload.wikimedia.org/wikipedia/commons/d/dd/Stack_Overflow_Home.png',
  'https://www.techtalkthai.com/wp-content/uploads/2019/05/stack_overflow_banner_1.jpg',
  'https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded',
  'https://upload.wikimedia.org/wikipedia/commons/d/dd/Stack_Overflow_Home.png',
  'https://www.techtalkthai.com/wp-content/uploads/2019/05/stack_overflow_banner_1.jpg',
  'https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded',
  'https://upload.wikimedia.org/wikipedia/commons/d/dd/Stack_Overflow_Home.png',
  'https://www.techtalkthai.com/wp-content/uploads/2019/05/stack_overflow_banner_1.jpg',
  'https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded',
  'https://upload.wikimedia.org/wikipedia/commons/d/dd/Stack_Overflow_Home.png',
  'https://www.techtalkthai.com/wp-content/uploads/2019/05/stack_overflow_banner_1.jpg',
  'https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded',
  'https://upload.wikimedia.org/wikipedia/commons/d/dd/Stack_Overflow_Home.png',
  'https://www.techtalkthai.com/wp-content/uploads/2019/05/stack_overflow_banner_1.jpg',
  'https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded',
  'https://upload.wikimedia.org/wikipedia/commons/d/dd/Stack_Overflow_Home.png',
  'https://www.techtalkthai.com/wp-content/uploads/2019/05/stack_overflow_banner_1.jpg',
  'https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded',
  'https://upload.wikimedia.org/wikipedia/commons/d/dd/Stack_Overflow_Home.png',
  'https://www.techtalkthai.com/wp-content/uploads/2019/05/stack_overflow_banner_1.jpg',
  'https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded',
  'https://upload.wikimedia.org/wikipedia/commons/d/dd/Stack_Overflow_Home.png',
]
